# Imports

In [1]:
import pandas as pd
import os

# SetUp

In [2]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

# Get Data

In [3]:
df_original = pd.read_parquet('../data/bronze/parquet-data/2022_LoL_esports_match_data_from_OraclesElixir.parquet')

In [4]:
df_original.head(2)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,playerid,teamname,teamid,champion,ban1,ban2,ban3,ban4,ban5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,firstbaron,barons,opp_barons,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15
0,ESPORTSTMNT01_2690210,complete,None,LCK CL,2022,Spring,0,2022-01-10 07:44:08,1,12.01,1,Blue,top,Soboro,oe:player:38e0af7278d6769d0c81d7c4b47ac1e,Fredit BRION Challengers,oe:team:68911b3329146587617ab2973106e23,Renekton,Karma,Caitlyn,Syndra,Thresh,Lulu,1713,0,2,3,2,9,19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3152,0.9807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15768.0,552.2942,0.278784,1072.3993,777.7933,8.0,0.2802,6.0,0.2102,5.0,26.0,0.9107,10934,7164.0,250.9282,0.253859,10275.0,NaN,231.0,220.0,11.0,NaN,NaN,8.0911,3228.0,4909.0,89.0,3176.0,4953.0,81.0,52.0,-44.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,5025.0,7560.0,135.0,4634.0,7215.0,121.0,391.0,345.0,14.0,0.0,1.0,0.0,0.0,1.0,0.0
1,ESPORTSTMNT01_2690210,complete,None,LCK CL,2022,Spring,0,2022-01-10 07:44:08,1,12.01,2,Blue,jng,Raptor,oe:player:637ed20b1e41be1c51bd1a4cb211357,Fredit BRION Challengers,oe:team:68911b3329146587617ab2973106e23,Xin Zhao,Karma,Caitlyn,Syndra,Thresh,Lulu,1713,0,2,5,6,9,19,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.3152,0.9807,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,11765.0,412.0841,0.208009,944.2732,650.1576,6.0,0.2102,18.0,0.6305,6.0,48.0,1.6813,9138,5368.0,188.0210,0.190220,8750.0,NaN,148.0,33.0,115.0,NaN,NaN,5.1839,3429.0,3484.0,58.0,2944.0,3052.0,63.0,485.0,432.0,-5.0,1.0,2.0,0.0,0.0,0.0,1.0,5366.0,5320.0,89.0,4825.0,5595.0,100.0,541.0,-275.0,-11.0,2.0,3.0,2.0,0.0,5.0,1.0

# Normalize table

## Games

In [6]:
games_cols = ['gameid', 'league', 'year', 'split', 'playoffs', 'patch', 'gamelength']
df_games = df_original[games_cols].drop_duplicates().reset_index(drop=True)

## Game_dates

In [47]:
game_dates_cols = ['gameid', 'date']
df_game_dates = df_original[game_dates_cols].drop_duplicates().reset_index(drop=True)

## Teams

In [10]:
teams_cols = ['teamid', 'teamname']
df_teams = df_original[teams_cols].drop_duplicates().reset_index(drop=True)

## Players

In [6]:
players_cols = ['playerid', 'playername']
df_players = df_original[players_cols].drop_duplicates().reset_index(drop=True)

## Participants

In [13]:
participants_cols = ['participantid', 'gameid', 'teamid', 'playerid', 'position', 'champion']
df_participants = df_original[participants_cols].drop_duplicates().reset_index(drop=True)

## Side

In [60]:
side_cols = ['teamid', 'position']
df_side = df_original[side_cols].drop_duplicates().reset_index(drop=True)

## Bans

In [64]:
bans_cols = ['gameid', 'teamid', 'ban1', 'ban2', 'ban3', 'ban4', 'ban5']
df_bans = df_original[bans_cols].drop_duplicates().reset_index(drop=True)

## Amount_matches

In [66]:
amount_matches_cols = ['gameid', 'game']
df_amount_matches = df_original[amount_matches_cols].drop_duplicates().reset_index(drop=True)

## GameStats

In [16]:
gamestats_cols = ['gameid', 'teamid', 'playerid', 'teamkills', 'teamdeaths', 'result']
df_gamestats = df_original[gamestats_cols].drop_duplicates().reset_index(drop=True)

## TeamStats

In [70]:
teamstats_cols = ['gameid', 'teamid', 'firstblood', 'firstdragon', 'firstherald','inhibitors', 'opp_inhibitors',
                  'totalgold', 'earnedgold', 'earned gpm', 'earnedgoldshare', 'goldspent', 'firstbaron', 'firsttower',
                  'firstmidtower', 'turretplates', 'opp_turretplates', 'firsttothreetowers', 'team kpm', 'ckpm', 'result']
df_teamstats = df_original[teamstats_cols].drop_duplicates().reset_index(drop=True)

## PlayerStats

In [18]:
playerstats_cols = ['gameid', 'participantid', 'playerid', 'kills', 'deaths', 'assists', 'doublekills', 'triplekills', 'quadrakills',
                    'pentakills', 'damagetochampions', 'damageshare', 'damagetakenperminute', 'damagemitigatedperminute', 'wardsplaced',
                    'wpm', 'wardskilled', 'controlwardsbought', 'visionscore']
df_playerstats = df_original[playerstats_cols].drop_duplicates().reset_index(drop=True)

## GoldandXPStats

In [5]:
goldandxpstats_cols = ['gameid', 'playerid', 'participantid', 'goldat10', 'xpat10', 'csat10', 'csdiffat10', 'golddiffat10', 'goldat15',
                    'xpat15', 'csat15', 'csdiffat15', 'golddiffat15', 'killsat10', 'assistsat10', 'deathsat10',
                    'opp_killsat10', 'opp_assistsat10', 'opp_deathsat10', 'killsat15', 'assistsat15', 'deathsat15',
                    'opp_killsat15', 'opp_assistsat15', 'opp_deathsat15']
df_goldandxpstats = df_original[goldandxpstats_cols].drop_duplicates().reset_index(drop=True)

                  gameid                                   playerid  participantid  goldat10  xpat10  csat10  csdiffat10  golddiffat10  goldat15  xpat15  csat15  csdiffat15  golddiffat15  killsat10  assistsat10  deathsat10  opp_killsat10  opp_assistsat10  opp_deathsat10  killsat15  assistsat15  deathsat15  opp_killsat15  opp_assistsat15  opp_deathsat15
0  ESPORTSTMNT01_2690210  oe:player:38e0af7278d6769d0c81d7c4b47ac1e              1    3228.0  4909.0    89.0         8.0          52.0    5025.0  7560.0   135.0        14.0         391.0        0.0          0.0         0.0            0.0              0.0             0.0        0.0          1.0         0.0            0.0              1.0             0.0
1  ESPORTSTMNT01_2690210  oe:player:637ed20b1e41be1c51bd1a4cb211357              2    3429.0  3484.0    58.0        -5.0         485.0    5366.0  5320.0    89.0       -11.0         541.0        1.0          2.0         0.0            0.0              0.0             1.0        2.0          3.0         2.0            0.0              5.0             1.0
2  ESPORTSTMNT01_2690210  oe:player:d1ae0e2f9f3ac1e0e0cdcb86504ca77              3    3283.0  4556.0    81.0         0.0         162.0    5118.0  6942.0   120.0         1.0        -475.0        0.0          1.0         0.0            0.0              0.0             1.0        0.0          3.0         0.0            3.0              3.0             2.0

## Dragons

In [12]:
dragons_cols = ['gameid', 'teamid', 'dragons', 'opp_dragons', 'elementaldrakes', 'opp_elementaldrakes',
                'infernals', 'mountains', 'clouds', 'oceans', 'chemtechs', 'hextechs', 'dragons (type unknown)',
                'elders', 'opp_elders']
df_dragons = df_original[dragons_cols].drop_duplicates().reset_index(drop=True)

## Heralds

In [96]:
heralds_cols = ['gameid', 'teamid', 'firstherald', 'heralds', 'opp_heralds']
df_heralds = df_original[heralds_cols].drop_duplicates().reset_index(drop=True).dropna()

## Barons

In [94]:
barons_cols = ['gameid', 'teamid', 'firstbaron', 'barons', 'opp_barons']
df_barons = df_original[barons_cols].drop_duplicates().reset_index(drop=True).dropna()

# Save the Data

In [22]:
# define the path to the folder
folder_path = '../data/silver/2022/'

# create the golder if it doesn't exist
if not os.path.exists(folder_path):
    os.makedirs(folder_path)
    
# Save the tables as Parquet files in the folder

df_games.to_parquet(os.path.join(folder_path, 'dim_games_2022.parquet'), index=False)
df_game_dates.to_parquet(os.path.join(folder_path, 'fact_game_date_2022.parquet'), index=False)
df_teams.to_parquet(os.path.join(folder_path, 'dim_teams_2022.parquet'), index=False)
df_players.to_parquet(os.path.join(folder_path, 'dim_players_2022.parquet'), index=False)
df_participants.to_parquet(os.path.join(folder_path, 'dim_participants_2022.parquet'), index=False)
df_side.to_parquet(os.path.join(folder_path, 'fact_side_2022.parquet'), index=False)
df_bans.to_parquet(os.path.join(folder_path, 'dim_bans_2022.parquet'), index=False)
df_amount_matches.to_parquet(os.path.join(folder_path, 'fact_amount_2022.parquet'), index=False)
df_gamestats.to_parquet(os.path.join(folder_path, 'fact_gamestats_2022.parquet'), index=False)
df_teamstats.to_parquet(os.path.join(folder_path, 'fact_teamstats_2022.parquet'), index=False)
df_playerstats.to_parquet(os.path.join(folder_path, 'fact_playerstats_2022.parquet'), index=False)
df_goldandxpstats.to_parquet(os.path.join(folder_path, 'fact_goldandxpstats_2022.parquet'), index=False)
df_dragons.to_parquet(os.path.join(folder_path, 'dim_dragons_2022.parquet'), index=False)
df_barons.to_parquet(os.path.join(folder_path, 'dim_barons_2022.parquet'), index=False)

In [9]:
df_goldandxpstats.head(3)

                  gameid                                   playerid  participantid  goldat10  xpat10  csat10  csdiffat10  golddiffat10  goldat15  xpat15  csat15  csdiffat15  golddiffat15  killsat10  assistsat10  deathsat10  opp_killsat10  opp_assistsat10  opp_deathsat10  killsat15  assistsat15  deathsat15  opp_killsat15  opp_assistsat15  opp_deathsat15
0  ESPORTSTMNT01_2690210  oe:player:38e0af7278d6769d0c81d7c4b47ac1e              1    3228.0  4909.0    89.0         8.0          52.0    5025.0  7560.0   135.0        14.0         391.0        0.0          0.0         0.0            0.0              0.0             0.0        0.0          1.0         0.0            0.0              1.0             0.0
1  ESPORTSTMNT01_2690210  oe:player:637ed20b1e41be1c51bd1a4cb211357              2    3429.0  3484.0    58.0        -5.0         485.0    5366.0  5320.0    89.0       -11.0         541.0        1.0          2.0         0.0            0.0              0.0             1.0        2.0          3.0         2.0            0.0              5.0             1.0
2  ESPORTSTMNT01_2690210  oe:player:d1ae0e2f9f3ac1e0e0cdcb86504ca77              3    3283.0  4556.0    81.0         0.0         162.0    5118.0  6942.0   120.0         1.0        -475.0        0.0          1.0         0.0            0.0              0.0             1.0        0.0          3.0         0.0            3.0              3.0             2.0